name: Build Project and Commit Changes

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/build-and-push.yml
      - index.html
      - 'src/**'
      - docs
      - pnpm-lock.yaml
      - '.node-version'
      - vite.config.ts
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-and-push.yml
      - index.html
      - 'src/**'
      - docs
      - pnpm-lock.yaml
      - '.node-version'
      - vite.config.ts

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint

      - name: Build project
        run: pnpm run build

      - name: Check for changes in docs directory
        id: check_changes
        run: |
          git add docs
          git status --porcelain docs | grep -q "^" && echo "changes=true" >> $GITHUB_OUTPUT || echo "changes=false" >> $GITHUB_OUTPUT

      - name: Commit and push changes if any
        if: steps.check_changes.outputs.changes == 'true' && github.event_name == 'pull_request'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Update build artifacts in docs directory" docs
          git push origin ${{ github.head_ref || github.ref_name }}

      - name: Commit and create pull_request changes if any
        if: steps.check_changes.outputs.changes == 'true' && github.event_name == 'push'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Update build artifacts in docs directory" docs
          git push -f origin ${{ github.head_ref || github.ref_name }}:build-and-push
          gh pr create --base main --head build-and-push --title "Update build artifacts in docs directory" --body "This PR updates the build artifacts in the docs directory."
